Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 1, in <module>
    from flask import Flask, request, redirect, send_file
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 79, in <module>
    print(f"\U0001f4e6 \u0110ã backup tracking.log sang: {backup_file}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e6' in position 0: character maps to <undefined>
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.42.24:5000
Press CTRL+C to quit
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 79, in <module>
    print(f"\U0001f4e6 \u0110ã backup tracking.log sang: {backup_file}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e6' in position 0: character maps to <undefined>
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.42.24:5000
Press CTRL+C to quit
83.147.15.111 - - [11/Jun/2025 11:13:29] "GET /open?email=123&rand={rand} HTTP/1.1" 304 -
83.147.15.111 - - [11/Jun/2025 11:14:16] "GET /click?email=123&target="https://zalo.me" HTTP/1.1" 302 -
83.147.15.111 - - [11/Jun/2025 11:14:21] "GET /click?email=123&target=https://zalo.me HTTP/1.1" 302 -
207.167.66.214 - - [11/Jun/2025 11:31:29] "CONNECT www.google.com:443 HTTP/1.1" 404 -
83.147.15.111 - - [11/Jun/2025 11:32:55] "GET /open?email=123123&rand={rand} HTTP/1.1" 200 -
74.125.209.70 - - [11/Jun/2025 11:34:08] "GET /open?email=tam.mapp04@gmail.com&rand={rand} HTTP/1.1" 200 -
83.147.15.111 - - [11/Jun/2025 11:34:12] "GET /click?target=https://infoasia.com.vn/&email=tam.mapp04@gmail.com HTTP/1.1" 302 -
83.147.15.111 - - [11/Jun/2025 11:34:13] "GET /click?target=https://zalo.me/0933823946&email=tam.mapp04@gmail.com HTTP/1.1" 302 -
83.147.15.111 - - [11/Jun/2025 11:34:14] "GET /click?target=https://infoasia.com.vn/&email=tam.mapp04@gmail.com HTTP/1.1" 302 -
Traceback (most recent call last):
  File "E:\Tracking_Email\Tracking_Email\tracking_server.py", line 79, in <module>
    print(f"\U0001f4e6 \u0110ã backup tracking.log sang: {backup_file}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4e6' in position 0: character maps to <undefined>
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.42.24:5000
Press CTRL+C to quit
160.191.86.229 - - [11/Jun/2025 11:41:35] "CONNECT www.google.com:443 HTTP/1.1" 404 -
199.204.96.90 - - [11/Jun/2025 11:57:11] "CONNECT www.google.com:443 HTTP/1.1" 404 -
65.49.1.158 - - [11/Jun/2025 13:00:48] "GET / HTTP/1.1" 404 -
65.49.1.159 - - [11/Jun/2025 13:01:13] "GET /favicon.ico HTTP/1.1" 404 -
160.191.86.229 - - [11/Jun/2025 13:38:44] "CONNECT www.google.com:443 HTTP/1.1" 404 -
207.167.66.214 - - [11/Jun/2025 14:03:08] "CONNECT www.google.com:443 HTTP/1.1" 404 -
